# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Ruff Check

on:
  pull_request:
    branches: ["main"]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
